export function buildOrchestratorSystemPrompt(availableReviewers: { id: string; name: string; description?: string; scopeHints?: string[] }[]): string {
  const reviewerList = availableReviewers
    .map(r => `- id: "${r.id}", name: "${r.name}"${r.description ? ', description: "' + r.description + '"' : ''}${r.scopeHints ? ', scopeHints: [' + r.scopeHints.join(', ') + ']' : ''}`)
    .join('\n');

  return `You are a PR review orchestrator. Given a pull request diff and changed files, decide which reviewers should analyze this PR.

## Available Reviewers
${reviewerList}

## Output Requirements

Return ONLY this JSON:
\`\`\`json
{
  "selectedReviewers": [
    {
      "reviewerId": "<id from the list above>",
      "reason": "<why this reviewer is relevant to the changes>"
    }
  ]
}
\`\`\`

Rules:
- Select only reviewers that are clearly relevant to the changed code
- If no reviewers are relevant, return an empty array
- Return ONLY the JSON`;
}

export function buildOrchestratorUserMessage(changedFiles: string[], diff: string): string {
  const diffPreview = diff.length > 12000 ? diff.slice(0, 12000) + '\n\n[...diff truncated...]' : diff;
  return `## Changed Files
${changedFiles.map(f => `- ${f}`).join('\n')}

## Diff
\`\`\`diff
${diffPreview}
\`\`\`

Which reviewers should analyze this PR?`;
}

export function buildPRReviewSystemPrompt(reviewerInstructions: string, reviewerId: string, reviewerName: string): string {
  return `You are a code reviewer performing a "${reviewerName}" review on a pull request.

${reviewerInstructions}

## Output Requirements

Return ONLY this JSON:
\`\`\`json
{
  "score": <number 0-100>,
  "summary": "<summary of PR review findings>",
  "findings": [
    {
      "id": "<unique finding ID>",
      "title": "<finding title>",
      "description": "<detailed description>",
      "priority": "<critical|high|medium|low|info>",
      "confidence": <0.0-1.0>,
      "filePath": "<relative file path>",
      "startLine": <line number in the changed file>,
      "endLine": <line number>,
      "evidence": ["<relevant code snippet>"],
      "recommendation": "<specific fix>",
      "tags": []
    }
  ]
}
\`\`\`

Rules:
- Focus primarily on the changed lines in the diff
- You may note issues in related unchanged files if critical
- filePath must be a real file from the PR
- startLine/endLine should reference lines in the changed file
- Finding ID prefix: ${reviewerId.toUpperCase().replace(/-/g, '_')}_PR`;
}

export function buildPRReviewUserMessage(
  diff: string,
  changedFiles: string[],
  additionalContext?: string
): string {
  const diffContent = diff.length > 16000 ? diff.slice(0, 16000) + '\n\n[...truncated...]' : diff;
  return `## Changed Files
${changedFiles.map(f => `- ${f}`).join('\n')}

## Pull Request Diff
\`\`\`diff
${diffContent}
\`\`\`
${additionalContext ? '\n## Additional Context\n' + additionalContext : ''}

Review the above changes and return the JSON result.`;
}

export function buildPRSummaryPrompt(findings: import('../../types/index').Finding[]): string {
  const bySeverity = {
    critical: findings.filter(f => f.priority === 'critical'),
    high: findings.filter(f => f.priority === 'high'),
    medium: findings.filter(f => f.priority === 'medium'),
    low: findings.filter(f => f.priority === 'low'),
    info: findings.filter(f => f.priority === 'info'),
  };
  return `## CodeOwl PR Review Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${bySeverity.critical.length} |
| 🟠 High | ${bySeverity.high.length} |
| 🟡 Medium | ${bySeverity.medium.length} |
| 🟢 Low | ${bySeverity.low.length} |
| ℹ️ Info | ${bySeverity.info.length} |

${findings.length === 0 ? '✅ No issues found.' : `**${findings.length} total findings.** See inline comments for details.`}

---
*Generated by [CodeOwl](https://github.com/codeowl/codeowl)*`;
}
